export const ROOM_SETUP_STATUS = {
  MEDIA_PERMISSION: "MEDIA_PERMISSION",
  ROOM_CONNECTED: "ROOM_CONNECTED",
  ROOM_DISCONNECTED: "ROOM_DISCONNECTED",
  ROOM_ERROR: "ROOM_ERROR",
  ROOM_READY: "ROOM_READY",
  ONGOING_CALL: "ONGOING_CALL",
  INCOMING_CALL: "INCOMING_CALL",
  CALLING: "CALLING",
};
